/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tab;

import javax.swing.JOptionPane;

/**
 *
 * @author Blade cva120
 */
public class AppTabuada extends javax.swing.JFrame {

    /**
     * Creates new form AppTabuada
     */
    public AppTabuada() {
        initComponents();
        combo.setEnabled(false);
        display.setEnabled(false);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        combo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoNum = new javax.swing.JTextField();
        bntLimpar = new javax.swing.JButton();
        bntSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TABUADA JAVA 2023");

        display.setEditable(false);
        display.setColumns(10);
        display.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        display.setForeground(new java.awt.Color(0, 0, 0));
        display.setLineWrap(true);
        display.setRows(10);
        display.setWrapStyleWord(true);
        jScrollPane1.setViewportView(display);

        combo.setBackground(new java.awt.Color(0, 153, 51));
        combo.setForeground(new java.awt.Color(0, 0, 0));
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adição", "Subtração", "Multiplicação", "Divisão" }));
        combo.setSelectedIndex(-1);
        combo.setToolTipText("");
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Escolha a tabuada para a operação");

        jLabel3.setText("Digite o número da tabuada que deseja exibir");

        campoNum.setBackground(new java.awt.Color(0, 153, 51));
        campoNum.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        campoNum.setForeground(new java.awt.Color(0, 0, 0));
        campoNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumActionPerformed(evt);
            }
        });
        campoNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoNumKeyPressed(evt);
            }
        });

        bntLimpar.setBackground(new java.awt.Color(0, 0, 153));
        bntLimpar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bntLimpar.setForeground(new java.awt.Color(255, 255, 255));
        bntLimpar.setText("Limpar");
        bntLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLimparActionPerformed(evt);
            }
        });

        bntSair.setBackground(new java.awt.Color(255, 51, 51));
        bntSair.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bntSair.setForeground(new java.awt.Color(255, 255, 255));
        bntSair.setText("Sair");
        bntSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bntLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(bntSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNum, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bntLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntSair)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    double res, num2;
    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
        double num1 = Double.parseDouble(campoNum.getText());
        int indice = combo.getSelectedIndex();

        //TABUADA DE ADIÇÃO
        if (indice == 0) {
            if (num1 < 10) {
                num2 = num1 + (10 - num1);
                for (int i = 0; i <= num2; i++) {
                    res = i + num1;
                    display.append(i + " + " + (int) num1 + " = " + (int) res + "\n");
                }
            } else {
                for (int i = 0; i <= num1; i++) {
                    res = i + num1;
                    display.append(i + " + " + (int) num1 + " = " + (int) res + "\n");
                }
            }
        }

        // TABUADA DE SUBTRAÇÃO
        if (indice == 1) {
            if (num1 < 10) {
                num2 = num1 + (10 - num1);
                for (int i = (int) num1; i <= (num2 + num1); i++) {
                    res = i - num1;
                    display.append(i + " - " + (int) num1 + " = " + (int) res + "\n");
                }
            } else {
                for (int i = (int) num1; i <= num1 + 10; i++) {
                    res = i - num1;
                    display.append(i + " - " + (int) num1 + " = " + (int) res + "\n");
                }
            }
        }

        // TABUADA DE MULTIPLICAÇÃO
        if (indice == 2) {
            if (num1 < 10) {
                num2 = num1 + (10 - num1);
                for (int i = 0; i <= num2; i++) {
                    res = i * num1;
                    display.append((int) num1 + " × " + i + " = " + (int) res + "\n");
                }
            } else {
                for (int i = 0; i <= num1; i++) {
                    res = i * num1;
                    display.append((int) num1 + " × " + i + " = " + (int) res + "\n");
                }
            }
        }

        // TABUADA DE DIVISÃO
        if (indice == 3) {
            if (num1 < 10) {
                num2 = num1 + (10 - num1);
                for (int i = (int) num1; i <= num2 + num1; i++) {
                    res = i / num1;
                    display.append(i + " ÷ " + (int) num1 + " = " + String.valueOf(res).format("%.3f", res) + "\n");
                }
            } else {
                for (int i = (int) num1; i <= num1 + 10; i++) {
                    res = i / num1;
                    display.append(i + " ÷ " + (int) num1 + " = " + String.valueOf(res).format("%.3f", res) + "\n");
                }
            }
        }
    }//GEN-LAST:event_comboActionPerformed

    private void campoNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumActionPerformed
        // TODO add your handling code here:
        if (campoNum.getText().isEmpty()) {
            combo.setEnabled(false);
            display.setEnabled(false);
        } else {
            combo.setEnabled(true);
            display.setEnabled(true);
        }
    }//GEN-LAST:event_campoNumActionPerformed

    private void bntLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLimparActionPerformed
        // TODO add your handling code here:
        display.setText("");
        campoNum.setText(null);
        combo.setEnabled(false);
        display.setEnabled(false);
        campoNum.requestFocus();
    }//GEN-LAST:event_bntLimparActionPerformed

    private void bntSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSairActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente sair? ");
        switch (resp) {
            case 0:
                System.exit(0);
            case 1:
                campoNum.requestFocus();
                display.setText("");
                campoNum.setText(null);
                combo.setEnabled(false);
                display.setEnabled(false);

            case 2:
                campoNum.requestFocus();
                display.setText("");
                campoNum.setText(null);
                combo.setEnabled(false);
                display.setEnabled(false);
        }
    }//GEN-LAST:event_bntSairActionPerformed

    private void campoNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNumKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppTabuada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppTabuada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppTabuada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppTabuada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppTabuada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntLimpar;
    private javax.swing.JButton bntSair;
    private javax.swing.JTextField campoNum;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JTextArea display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
